export enum OrderStatusModel {
    PENDING_PROOF = "PENDING_PROOF",
    PENDING_VERIFICATION = "PENDING_VERIFICATION",
    VERIFIED = "VERIFIED",
    FAILED_PAYMENT = "FAILED_PAYMENT",
    CANCELLED = "CANCELLED",
    PROCESSING = "PROCESSING",
    SHIPPING = "SHIPPING",
    CONFIRMED = "CONFIRMED",
}